#! /usr/bin/env zsh
RUBY=(/usr/bin/env ruby -p -e)
subst='$_.gsub!(/&<var>amp<\/var>;/, %q|<var>&amp;</var>|)'
subst2='$_.gsub!(/&<var>lt<\/var>;/, %q|<var>&lt;</var>|)'
RD=( rd2 -r rd/rd2html-lib --with-css=rubyStyle.css )

$RD --html-title="DBD Specification Version 0.1 (Draft)" DBD_SPEC  | $RUBY "$subst" | $RUBY "$subst2"  > DBD_SPEC.html
$RD --html-title="DBI Specification Version 0.5 (Draft)" DBI_SPEC  | $RUBY "$subst" | $RUBY "$subst2"  > DBI_SPEC.html

